### ISSUE TITLE
Issue with nested itemscopes

### ISSUE THREAD

**Issue by alexkart** [linclark/MicrodataPHP#10]
It seems there's an issue with nested itemscopes
It do not extract itemprops in nested itemscopes

It looks like this:

```
[location] => Array
 (
  [0] => stdClass Object
   (
    [properties] => Array
     (
      [address] => Array
       (
        [0] => ERROR
       )
...
```

But there are properties inside "address":

```
[location] => Array
 (
  [0] => stdClass Object
   (
    [properties] => Array
     (
      [address] => Array
       (
        [0] => stdClass Object
         (
          [properties] => Array
           (
            [streetAddress] => Array
             (
              [0] => Rheinstraße 66
             )
...
```

html:

```
    <div class="content-block clearfix" id="location" itemprop="location" itemscope itemtype="http://schema.org/Place">
        <div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
            <strong>Addresse:</strong>
            <span itemprop="streetAddress">Rheinstraße 66</span>,
            <span itemprop="postalCode">55116</span>
            <span itemprop="addressLocality">Mainz</span>,
            <span itemprop="addressCountry">Germany</span>
        </div>
    </div>
```

This line of code https://github.com/linclark/MicrodataPHP/blob/2.0.x/src/MicrodataPhp.php#L112

**Comment by linclark** [comment]
Hm, I don't have that problem. 

I added an automated test for it using a slightly modified version of your snippet. The test passes.

Let me know if you are still running into this problem and we can try to debug it further.

**Comment by alexkart** [comment]
sorry, I have shown just a part of my html, there is another parent itemscope in my html:

```
<div class="wrapper" itemscope itemtype="http://schema.org/BusinessEvent" itemref="start-date end-date">
    <div class="content-block clearfix" id="location" itemprop="location" itemscope itemtype="http://schema.org/Place">
        <div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
            <strong>Addresse:</strong>
            <span itemprop="streetAddress">Rheinstraße 66</span>,
            <span itemprop="postalCode">55116</span>
            <span itemprop="addressLocality">Mainz</span>,
            <span itemprop="addressCountry">Germany</span>
        </div>
    </div>
</div>
```

with this snippet the test will not pass

**Comment by linclark** [comment]
Hm, you seem to be correct. Adding in the third level does cause an error. I'll have to look into this later. Thanks for pinpointing the issue.

**Comment by linclark** [comment]
So I found the issue and fixed it. It works with the HTML that you provided in my test, so it should work for you, but let me know if it doesn't.

Thanks for the helpful bug report.

**Comment by alexkart** [comment]
Yes, it works with the HTML that I provided, but now there is a problem with another example.

Look at the source code of this html page:
https://194.28.87.206/microdataphp/example3.html

Extracted structured data should look like this:
https://194.28.87.206/microdataphp/test1.php

But with your library it looks incorrect:
https://194.28.87.206/microdataphp/test2.php

**Comment by linclark** [comment]
I'll take a look. Please open a new issue and include the code snippets directly in the page as you did in this one.
