### ISSUE TITLE
URL should not go to the MicrodataPhpDOMDocument constructor

### ISSUE THREAD

**Issue by keyworq** [linclark/MicrodataPHP#4]
It looks like there may be an issue with line 30 of "MicrodataPhp.php" where it reads "new MicrodataPhpDOMDocument($url)": the URL should probably not be specified as the constructor argument.  Looking at the PHP documentation for the base constructor (i.e., "DOMDocument::__construct"), the argument is actually supposed to be "the version number of the document".  Simply providing no argument appears to work just fine.

**Comment by linclark** [comment]
Sorry for the delayed response, I am just getting back to this project now to release a 2.0 version. You were totally right, I've made the change. Thanks!
