### ISSUE TITLE
Bug: Failed to parse all nested items

### ISSUE THREAD

**Issue by thachp** [linclark/MicrodataPHP#9]
Dom parser failed to parse items inside items.  For example, it failed to parse a collection of reviews of a restaurant webpage.

Example URL: www.yelp.com/biz/paseo-seattle
Expect:  a list of restaurant reviews as well as restaurant profile.
Actual:  It was not able to parse any of the review items.
Repo Branch:  2.0.x

This tool is able to parse the reviews.  https://webmaster.yandex.com/microtest.xml

**Comment by linclark** [comment]
It doesn't fail to parse all nested items. For example, it parses the address of the `http://schema.org/LocalBusiness` item, which is a `http://schema.org/PostalAddress` item.

**Comment by linclark** [comment]
I haven't had a chance to look too closely, but it looks like invalid microdata. It looks like the following block is not nested within another microdata item:

```
<div class="review review-with-no-actions" data-review-id="SL_IlWtUmYMXoZbMsIetbw" itemprop="review" itemscope itemtype="http://schema.org/Review">
```

If it used `itemref`, then that would be ok because that would make it a property of some item, and thus not a top level item. However, since it doesn't it violates the following from the spec:

```
A document must not contain any elements that have an itemprop attribute that would not be found to be a property of any of the items in that document were their properties all to be determined.
```

Google and other search engines tend to be more flexible in the markup that they will accept, so they probably have some special code to compensate.

**Comment by thachp** [comment]
Thank you for looking into this.  You may be correct.  I implemented your package on our website at http://www.betayum.com/validator.  Tried this example markup codes, and it works.  It has no problem parsing the nested items.  Looks like a markup error on Yelp's part.  

```
<div itemscope itemtype="http://schema.betayum.com/menu">
    <h1 itemprop="name">Lunch Menus</h1>
    <p itemprop="description">a menu description here.</p>

    <div itemscope itemtype="http://schema.betayum.com/menuGroup">
        <h3 itemprop="name">Pizzas</h3>
        <p itemprop="description">a menu group description here.</p>
        <ul>
            <li itemscope itemtype="http://schema.betayum.com/menuItem">
                <h5 itemprop="name">Pepperoni Pizza</h5>
                <p itemprop="description">cucumber and seaweed with rice vinegar</p>
                <span itemprop="price">$5.99</span>
            </li>
            <li itemscope itemtype="http://schema.betayum.com/menuItem">
                <h5 itemprop="name"> Hawaiian Pizza</h5>
                <p itemprop="description">cucumber and seaweed with rice vinegar</p>
                <span itemprop="price">$8.99</span>
            </li>
             <li itemscope itemtype="http://schema.betayum.com/menuItem">
                <h5 itemprop="name">Cheese Pizza</h5>
                <p itemprop="description">cucumber and seaweed with rice vinegar</p>
                <span itemprop="price">$3.99</span>
            </li>
        </ul>
    </div>
<div>  
```

**Comment by linclark** [comment]
Great, thanks for confirming. I also checked out the site, very cool!
